name = "ubiquitous-dory"

[[devices]]
name = "utl01"
model = "flatcar_linux"
cpu_count = 2
memory = 4096
files = [
  { source = "files/ssh/k8s_ssh_key", destination = "/home/sherpa/.ssh/k8s_ssh_key", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/ssh/k8s_ssh_key.pub", destination = "/home/sherpa/.ssh/k8s_ssh_key.pub", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/ssh/k8s_ssh_config", destination = "/home/sherpa/.ssh/config", user = "sherpa", group = "sherpa", permissions = 400 },
]


[[devices]]
name = "ctl01"
model = "flatcar_linux"
cpu_count = 2
memory = 4096
files = [
  { source = "files/certs/ctl01.crt", destination = "/home/sherpa/ctl01.crt", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/ctl01.csr", destination = "/home/sherpa/ctl01.csr", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/ctl01.key", destination = "/home/sherpa/ctl01.key", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/ca.key", destination = "/home/sherpa/ca.key", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/ca.crt", destination = "/home/sherpa/ca.crt", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/kube-api-server.key", destination = "/home/sherpa/kube-api-server.key", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/kube-api-server.crt", destination = "/home/sherpa/kube-api-server.crt", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/service-accounts.key", destination = "/home/sherpa/service-accounts.key", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/configs/admin.kubeconfig", destination = "/home/sherpa/admin.kubeconfig", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/configs/kube-controller-manager.kubeconfig", destination = "/home/sherpa/kube-controller-manager.kubeconfig", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/configs/kube-scheduler.kubeconfig", destination = "/home/sherpa/kube-scheduler.kubeconfig", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/configs/encryption-config.yaml", destination = "/home/sherpa/encryption-config.yaml", user = "sherpa", group = "sherpa", permissions = 400 },
]
ssh_authorized_key_files = [{ source = "files/ssh/k8s_ssh_key.pub" }]

[[devices]]
name = "wrk01"
model = "flatcar_linux"
cpu_count = 2
memory = 4096
files = [
  { source = "files/certs/wrk01.crt", destination = "/home/sherpa/wrk01.crt", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/wrk01.csr", destination = "/home/sherpa/wrk01.csr", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/wrk01.key", destination = "/home/sherpa/wrk01.key", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/ca.crt", destination = "/var/lib/kubelet/ca.crt", user = "root", group = "root", permissions = 400 },
  { source = "files/certs/wrk01.crt", destination = "/var/lib/kubelet/kubelet.crt", user = "root", group = "root", permissions = 400 },
  { source = "files/certs/wrk01.key", destination = "/var/lib/kubelet/kubelet.key", user = "root", group = "root", permissions = 400 },
  { source = "files/configs/kube-proxy.kubeconfig", destination = "/var/lib/kube-proxy/kubeconfig", user = "root", group = "root", permissions = 400 },
  { source = "files/configs/wrk01.kubeconfig", destination = "/var/lib/kubelet/kubeconfig", user = "root", group = "root", permissions = 400 },
]
ssh_authorized_key_files = [{ source = "files/ssh/k8s_ssh_key.pub" }]

[[devices]]
name = "wrk02"
model = "flatcar_linux"
cpu_count = 2
memory = 4096
files = [
  { source = "files/certs/wrk02.crt", destination = "/home/sherpa/wrk02.crt", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/wrk02.csr", destination = "/home/sherpa/wrk02.csr", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/wrk02.key", destination = "/home/sherpa/wrk02.key", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/ca.crt", destination = "/var/lib/kubelet/ca.crt", user = "root", group = "root", permissions = 400 },
  { source = "files/certs/wrk02.crt", destination = "/var/lib/kubelet/kubelet.crt", user = "root", group = "root", permissions = 400 },
  { source = "files/certs/wrk02.key", destination = "/var/lib/kubelet/kubelet.key", user = "root", group = "root", permissions = 400 },
  { source = "files/configs/kube-proxy.kubeconfig", destination = "/var/lib/kube-proxy/kubeconfig", user = "root", group = "root", permissions = 400 },
  { source = "files/configs/wrk02.kubeconfig", destination = "/var/lib/kubelet/kubeconfig", user = "root", group = "root", permissions = 400 },
]
ssh_authorized_key_files = [{ source = "files/ssh/k8s_ssh_key.pub" }]

[[devices]]
name = "wrk03"
model = "flatcar_linux"
cpu_count = 2
memory = 4096
files = [
  { source = "files/certs/wrk03.crt", destination = "/home/sherpa/wrk03.crt", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/wrk03.csr", destination = "/home/sherpa/wrk03.csr", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/wrk03.key", destination = "/home/sherpa/wrk03.key", user = "sherpa", group = "sherpa", permissions = 400 },
  { source = "files/certs/ca.crt", destination = "/var/lib/kubelet/ca.crt", user = "root", group = "root", permissions = 400 },
  { source = "files/certs/wrk03.crt", destination = "/var/lib/kubelet/kubelet.crt", user = "root", group = "root", permissions = 400 },
  { source = "files/certs/wrk03.key", destination = "/var/lib/kubelet/kubelet.key", user = "root", group = "root", permissions = 400 },
  { source = "files/configs/kube-proxy.kubeconfig", destination = "/var/lib/kube-proxy/kubeconfig", user = "root", group = "root", permissions = 400 },
  { source = "files/configs/wrk03.kubeconfig", destination = "/var/lib/kubelet/kubeconfig", user = "root", group = "root", permissions = 400 },
]
ssh_authorized_key_files = [{ source = "files/ssh/k8s_ssh_key.pub" }]

links = [
  # { dev_a = "dev01", int_a = 1, dev_b = "dev02", int_b = 1 },
]
