kind: EncryptionConfiguration
apiVersion: apiserver.config.k8s.io/v1
resources:
    - resources:
          - secrets
      providers:
          - aescbc:
                keys:
                    - name: key1
                      secret: KQglHyQcWXybO2j9L2jbUaft1o7WV9dGkJufHxv3C18=
          - identity: {}
